export const NaturezaOperacaoEnum = [
  { value: '5351', text: '5351 - Prestação de serviço de transporte para execução de serviço da mesma natureza' },
  { value: '5352', text: '5352 - Prestação de serviço de transporte a estabelecimento industrial' },
  { value: '5353', text: '5353 - Prestação de serviço de transporte a estabelecimento comercial' },
  { value: '5354', text: '5354 - Prestação de serviço de transporte a estabelecimento de prestador de serviço de comunicação' },
  { value: '5355', text: '5355 - Prestação de serviço de transporte a estabelecimento de geradora ou de distribuidora de energia elétrica' },
  { value: '5356', text: '5356 - Prestação de serviço de transporte a estabelecimento de produtor rural' },
  { value: '5357', text: '5357 - Prestação de serviço de transporte a não contribuinte' },
  { value: '5359', text: '5359 - Prestação de serviço de transporte a contribuinte ou a não contribuinte quando a mercadoria transportada está dispensada de emissão de nota fiscal.' },
  { value: '5360', text: '5360 - Prestação de serviço de transporte a contribuinte substituto em relação ao serviço de transporte' },
  { value: '5601', text: '5601 - Transferência de crédito de ICMS acumulado' },
  { value: '5602', text: '5602 - Transferência de saldo credor de ICMS para outro estabelecimento da mesma empresa, destinado à compensação de saldo devedor de ICMS' },
  { value: '5603', text: '5603 - Ressarcimento de ICMS retido por substituição tributária' },
  { value: '5605', text: '5605 - Transferência de saldo devedor de ICMS de outro estabelecimento da mesma empresa.' },
  { value: '5606', text: '5606 - Utilização de saldo credor de ICMS para extinção por compensação de débitos fiscais.' },
  { value: '5932', text: '5932 - Prestação de serviço de transporte iniciada em unidade da Federação diversa daquela onde inscrito o prestador' },
  { value: '5949', text: '5949 - Outra saída de mercadoria ou prestação de serviço não especificado' },
  { value: '6351', text: '6351 - Prestação de serviço de transporte para execução de serviço da mesma natureza' },
  { value: '6352', text: '6352 - Prestação de serviço de transporte a estabelecimento industrial' },
  { value: '6353', text: '6353 - Prestação de serviço de transporte a estabelecimento comercial' },
  { value: '6354', text: '6354 - Prestação de serviço de transporte a estabelecimento de prestador de serviço de comunicação' },
  { value: '6355', text: '6355 - Prestação de serviço de transporte a estabelecimento de geradora ou de distribuidora de energia elétrica' },
  { value: '6356', text: '6356 - Prestação de serviço de transporte a estabelecimento de produtor rural' },
  { value: '6357', text: '6357 - Prestação de serviço de transporte a não contribuinte' },
  { value: '6359', text: '6359 - Prestação de serviço de transporte a contribuinte ou a não contribuinte quando a mercadoria transportada está dispensada de emissão de nota fiscal.' },
  { value: '6360', text: '6360 - Prestação de serviço de transporte a contribuinte substituto em relação ao serviço de transporte.' },
  { value: '6603', text: '6603 - Ressarcimento de ICMS retido por substituição tributária' },
  { value: '6932', text: '6932 - Prestação de serviço de transporte iniciada em unidade da Federação diversa daquela onde inscrito o prestador' },
  { value: '6949', text: '6949 - Outra saída de mercadoria ou prestação de serviço não especificado' },
  { value: '7358', text: '7358 - Prestação de serviço de transporte' },
  { value: '7949', text: '7949 - Outra saída de mercadoria ou prestação de serviço não especificado' }
];


export const NaturezaOperacaoDescricao = {
  '5351': 'Prestação de serviço de transporte para execução de serviço da mesma natureza',
  '5352': 'Prestação de serviço de transporte a estabelecimento industrial',
  '5353': 'Prestação de serviço de transporte a estabelecimento comercial',
  '5354': 'Prestação de serviço de transporte a estabelecimento de prestador de serviço de comunicação',
  '5355': 'Prestação de serviço de transporte a estabelecimento de geradora ou de distribuidora de energia elétrica',
  '5356': 'Prestação de serviço de transporte a estabelecimento de produtor rural',
  '5357': 'Prestação de serviço de transporte a não contribuinte',
  '5359': 'Prestação de serviço de transporte a contribuinte ou a não contribuinte quando a mercadoria transportada está dispensada de emissão de nota fiscal.',
  '5360': 'Prestação de serviço de transporte a contribuinte substituto em relação ao serviço de transporte',
  '5601': 'Transferência de crédito de ICMS acumulado',
  '5602': 'Transferência de saldo credor de ICMS para outro estabelecimento da mesma empresa, destinado à compensação de saldo devedor de ICMS',
  '5603': 'Ressarcimento de ICMS retido por substituição tributária',
  '5605': 'Transferência de saldo devedor de ICMS de outro estabelecimento da mesma empresa.',
  '5606': 'Utilização de saldo credor de ICMS para extinção por compensação de débitos fiscais.',
  '5932': 'Prestação de serviço de transporte iniciada em unidade da Federação diversa daquela onde inscrito o prestador',
  '5949': 'Outra saída de mercadoria ou prestação de serviço não especificado',
  '6351': 'Prestação de serviço de transporte para execução de serviço da mesma natureza',
  '6352': 'Prestação de serviço de transporte a estabelecimento industrial',
  '6353': 'Prestação de serviço de transporte a estabelecimento comercial',
  '6354': 'Prestação de serviço de transporte a estabelecimento de prestador de serviço de comunicação',
  '6355': 'Prestação de serviço de transporte a estabelecimento de geradora ou de distribuidora de energia elétrica',
  '6356': 'Prestação de serviço de transporte a estabelecimento de produtor rural',
  '6357': 'Prestação de serviço de transporte a não contribuinte',
  '6359': 'Prestação de serviço de transporte a contribuinte ou a não contribuinte quando a mercadoria transportada está dispensada de emissão de nota fiscal.',
  '6360': 'Prestação de serviço de transporte a contribuinte substituto em relação ao serviço de transporte.',
  '6603': 'Ressarcimento de ICMS retido por substituição tributária',
  '6932': 'Prestação de serviço de transporte iniciada em unidade da Federação diversa daquela onde inscrito o prestador',
  '6949': 'Outra saída de mercadoria ou prestação de serviço não especificado',
  '7358': 'Prestação de serviço de transporte',
  '7949': 'Outra saída de mercadoria ou prestação de serviço não especificado'
};
